apiVersion: v1
kind: BuildConfig
metadata:
  name: appimage
spec:
  runPolicy: Serial
  triggers:
  - github:
      secret: L2iO2Azdk9QrhVtGUegR
    type: GitHub
  - generic:
      secret: 4vubWdz4MO6IF50R4xOv
    type: Generic
  - type: ConfigChange
  - imageChange: {}
    type: ImageChange
  source:
    git:
      uri: https://github.com/43books/ch09-apps.git
      ref: master
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: builderimage:latest
    type: Source
  output:
    to:
      kind: ImageStreamTag
      name: appimage:latest

