apiVersion: v1
kind: BuildConfig
metadata:
  name: builderimage
spec:
  triggers:
  - imageChange: {}
    type: ImageChange
  source:
    git:
      uri: https://github.com/43books/ch09-builderimage.git
    type: Git
  strategy:
    type: Docker
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: base-centos7:latest
  output:
    to:
      kind: ImageStreamTag
      name: builderimage:latest
