apiVersion: v1
kind: Pod
metadata:
  name: downward-api-volume
  labels:
    foo: bar
spec:
  containers:
  - name: main
    image: busybox
    command: ["sleep", "9999999"]
    volumeMounts:
    - name: downward
      mountPath: /etc/downward
  volumes:
  - name: downward
    downwardAPI:
      items:
      - path: "podName"
        fieldRef:
          fieldPath: metadata.name
      - path: "podNamespace"
        fieldRef:
          fieldPath: metadata.namespace
      - path: "labels"
        fieldRef:
          fieldPath: metadata.labels

