apiVersion: v1
kind: Pod
metadata:
  name: emptydir-volume
spec:
  containers:
  - name: main
    image: centos:7
    command:
      - "bin/bash"
      - "-c"
      - "sleep 10000"
    volumeMounts:
      - name: share
        mountPath: "/tmp/share"
  - name: support
    image: centos:7
    command:
      - "bin/bash"
      - "-c"
      - "sleep 10000"
    volumeMounts:
      - name: share
        mountPath: "/tmp/data"
  volumes:
  - name: share
    emptyDir: {}
