apiVersion: v1
kind: Pod
metadata:
  name: nginx-configmap-volume
spec:
  containers:
  - image: nginx:alpine
    name: web
    volumeMounts:
    - name: config
      mountPath: /etc/nginx/conf.d  # (1)
      readOnly: true
  volumes:
  - name: config
    configMap:   # (2)
      name: nginx-custom
