kind: EgressNetworkPolicy
apiVersion: v1
metadata:
  name: allow-intra
spec:
  egress:
  - type: Allow
    to:
      cidrSelector: 192.168.1.0/24
  - type: Allow
    to:
    dnsName: www.google.com
  - type: Deny
    to:
      cidrSelector: 0.0.0.0/0
